[project]
name = "100-day-challenge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.142.2",
    "logging>=0.4.9.6",
    "requests>=2.34.2",
    "uvicorn[standard]>=0.54.0",
]

[tool.uv.workspace]
members = [
    "mini_1",
]
